Add iomanip include for formatting in player progress bar
fix missing include:
 error: ‘setprecision’ is not a member of ‘std’
  149 |       "[" << std::fixed << std::setprecision(9) << progress_current_time_secs <<


Signed-off-by: mosfet80 <10235105+mosfet80@users.noreply.github.com>