Remove "sudo pip uninstall -y mypy" since it is not installed with pip
Addressing the error message:
Found existing installation: mypy 1.9.0
ERROR: Cannot uninstall mypy 1.9.0, RECORD file not found. Hint:
The package was installed by debian.

Signed-off-by: Michael Orlov <michael.orlov@apex.ai>