Update CI scripts to use Ubuntu Noble distros and bump action scripts to latest versions (#1709)
* Use Ubuntu Noble distros for ci jobs on rolling

Signed-off-by: Michael Orlov <michael.orlov@apex.ai>

* Bump actions-ros-lint to version 0.1.3 and actions/checkout to v4

Signed-off-by: Michael Orlov <michael.orlov@apex.ai>

* Exclude cppcheck from CI due to known issue that it is very slow

See https://github.com/ament/ament_lint/pull/345 for details.

Signed-off-by: Michael Orlov <michael.orlov@apex.ai>

* Bump mypy to version 1.9.0-4ubuntu1 to be aligned with Noble

- Also add `--break-system-packages` to avoid error during pip uninstall

Signed-off-by: Michael Orlov <michael.orlov@apex.ai>

* Remove "sudo pip uninstall -y mypy" since it is not installed with pip

Addressing the error message:
Found existing installation: mypy 1.9.0
ERROR: Cannot uninstall mypy 1.9.0, RECORD file not found. Hint:
The package was installed by debian.

Signed-off-by: Michael Orlov <michael.orlov@apex.ai>

* Revert "Bump mypy to version 1.9.0-4ubuntu1 to be aligned with Noble"

This reverts commit b5aa0186

Signed-off-by: Michael Orlov <michael.orlov@apex.ai>

* Fixes for new mypy (Ubuntu 24.04) (#1763)

* Apply new stubgen changes

Signed-off-by: Roman Sokolkov <rsokolkov@gmail.com>

* Update CI script and README.md

Signed-off-by: Roman Sokolkov <rsokolkov@gmail.com>

---------

Signed-off-by: Roman Sokolkov <rsokolkov@gmail.com>

* Remove "--break-system-packages" flag from mypy install in README.md

- Rationale: On Ubuntu 22.04 is an older version of the pip3 and python
version which doesn't have this flag.
- Also removed sudo before "pip3 install -U mypy==1.9" in README.md

Signed-off-by: Michael Orlov <michael.orlov@apex.ai>

---------

Signed-off-by: Michael Orlov <michael.orlov@apex.ai>
Signed-off-by: Roman Sokolkov <rsokolkov@gmail.com>
Co-authored-by: Roman <rsokolkov@gmail.com>