Fixes clang compiler error introduced by #1404.
```
rosbag2_py/src/rosbag2_py/_reader.cpp:48:37: error: non-const lvalue reference to type 'rosbag2_cpp::ConverterOptions' cannot bind to a temporary of type 'rosbag2_cpp::ConverterOptions'
    rosbag2_cpp::ConverterOptions & converter_options = rosbag2_cpp::ConverterOptions())
                                    ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

A non-const lvalue reference cannot be bound to a temporary.

Signed-off-by: Halvor Platou <halvor.platou@zeabuz.com>