Fix reindex duration bug when bag file durations overlap (#2036) (#2106)
* Fix reindex duration bug when bag files overlap.



* Set the duration instead of adding it.



* Fixing some linting.



* Cleanups in test_reindexer.cpp



* Attempt to fix Windows build error

Fix for error:
 "test_reindexer.cpp(50,1): error C2679: binary '=': no operator found
 which takes a right-hand operand of type
 'std::chrono::system_clock::time_point' (or there is no acceptable
 conversion)



---------





(cherry picked from commit 8607af5a21352fa51381ff84c2b9f637937655fc)

Signed-off-by: Chui Vanfleet <chui.vanfleet@epiroc.com>
Signed-off-by: Michael Orlov <morlovmr@gmail.com>
Co-authored-by: Chui Vanfleet <26607858+ChuiVanfleet@users.noreply.github.com>
Co-authored-by: Chui Vanfleet <chui.vanfleet@epiroc.com>
Co-authored-by: Michael Orlov <morlovmr@gmail.com>